=== osawa-koki/mandelbrot.kt/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="config">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="mandelbrot" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="width" type="xsd:integer"/>
            <xsd:element name="height" type="xsd:integer"/>
            <xsd:element name="x_min" type="xsd:float"/>
            <xsd:element name="x_max" type="xsd:float"/>
            <xsd:element name="y_min" type="xsd:float"/>
            <xsd:element name="y_max" type="xsd:float"/>
            <xsd:element name="iteration" type="xsd:integer"/>
            <xsd:element name="incremental_step" type="xsd:integer"/>
            <xsd:element name="color_mode">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="RED" />
                  <xsd:enumeration value="GREEN" />
                  <xsd:enumeration value="BLUE" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="threshold" type="xsd:integer"/>
            <xsd:element name="output" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== osawa-koki/mandelbrot.kt/config.xml
<?xml version="1.0" encoding="utf-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>RED</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>GREEN</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>BLUE</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>RED</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>GREEN</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>BLUE</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>RED</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>


  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>GREEN</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>


  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <color_mode>BLUE</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>RED</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>


  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>GREEN</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>


  <mandelbrot>
    <width>2048</width>
    <height>2048</height>
    <x_min>-0.9</x_min>
    <x_max>-0.6</x_max>
    <y_min>-0.4</y_min>
    <y_max>0.1</y_max>
    <iteration>100</iteration>
    <incremental_step>10</incremental_step>
    <color_mode>BLUE</color_mode>
    <threshold>10</threshold>
    <output>#{GUID}.png</output>
  </mandelbrot>
</config>
